// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLB1qhWL3NbiZYKre_23nuwt-iswBCUbs',
    appId: '1:602530602464:web:b4a1c26017a1f8ccaf5f85',
    messagingSenderId: '602530602464',
    projectId: 'fir-odev-ce469',
    authDomain: 'fir-odev-ce469.firebaseapp.com',
    storageBucket: 'fir-odev-ce469.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUu8Ff924lvEL-dvg4IgbhRsPrUOhvmg',
    appId: '1:602530602464:android:69846a7872523326af5f85',
    messagingSenderId: '602530602464',
    projectId: 'fir-odev-ce469',
    storageBucket: 'fir-odev-ce469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9B34AqUP6Aiod11TYP-h8BkMocTP58Z8',
    appId: '1:602530602464:ios:61193d083893776baf5f85',
    messagingSenderId: '602530602464',
    projectId: 'fir-odev-ce469',
    storageBucket: 'fir-odev-ce469.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9B34AqUP6Aiod11TYP-h8BkMocTP58Z8',
    appId: '1:602530602464:ios:176b519e4676f900af5f85',
    messagingSenderId: '602530602464',
    projectId: 'fir-odev-ce469',
    storageBucket: 'fir-odev-ce469.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
